# Generated by Django 5.0.2 on 2024-03-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rezerwacje',
        ),
        migrations.DeleteModel(
            name='uslugi',
        ),
        migrations.DeleteModel(
            name='uzytkownicy',
        ),
    ]
